### ISSUE TITLE
商店中不可以打开方块菜单，不完全支持自定义

### ISSUE THREAD

**Issue by ClayCoffee** [Ldcr993519867/BedwarsXP#11]
`在商店里打不开方块的菜单,起床战争已经更新到最新版本，本插件也已经更新到最新版本。
服务端核心:PaperSpigot
版本:1.12.2、
报错

> [19:19:34 INFO]: [BedwarsXP] 为地图 吃豆豆 替换经验商店成功!
[19:19:37 ERROR]: Could not pass event InventoryClickEvent to BedwarsRel v1.3.6
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
        at ldcr.BedwarsXP.XPShop.XPItemShop.toItemStack(XPItemShop.java:229) ~[?
:?]
        at ldcr.BedwarsXP.XPShop.XPItemShop.openBuyInventory(XPItemShop.java:209
) ~[?:?]
        at ldcr.BedwarsXP.XPShop.XPItemShop.handleCategoryInventoryClick(XPItemS
hop.java:190) ~[?:?]
        at ldcr.BedwarsXP.XPShop.XPItemShop.handleInventoryClick(XPItemShop.java
:140) ~[?:?]
        at io.github.bedwarsrel.listener.PlayerListener.onIngameInventoryClick(P
layerListener.java:621) ~[?:?]
        at io.github.bedwarsrel.listener.PlayerListener.onInventoryClick(PlayerL
istener.java:657) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
ecutor342.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Pa
perSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
8) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:527) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:512) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:1981) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33
) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10
) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMain
Thread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.12.2-b1474.jar:git-Paper
-1474]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpig
ot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
843) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
427) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
767) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:665) [PaperSpigot-1.12.2-b1474.jar:git-Paper-1474]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

-----------------------------------------------------------------
2.自定义问题
我在配置文件中并没有声明铜的价格，且起床资源配置内没有铜。
但是插件自动给我加了铜，而且价值0元..
stm

总之，希望解决

**Comment by SakuraKoi** [comment]
第一个问题应当是spigot1.12改了api的原因, 将于下一个版本修复
第二个问题请确定您的Bedwarsrel配置文件中resource节下没有铜资源
本插件是直接遍历resource节下所有资源信息的,不应该凭空出现资源

**Comment by SakuraKoi** [comment]
已修复
