### ISSUE TITLE
Actionbar 1.12.2报错

### ISSUE THREAD

**Issue by SakuraKoi** [Ldcr993519867/BedwarsXP#12]
> java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_12_R1.IChatBaseComponent, byte)
>  at java.lang.Class.getConstructor0(Class.java:3082)
>  at java.lang.Class.getConstructor(Class.java:1825)
>  at ldcr.BedwarsXP.Utils.ActionBarUtils.sendActionBar(ActionBarUtils.java:56)

**Comment by SakuraKoi** [comment]
fixed
