### ISSUE TITLE
BWXP2.0 与 BedwarsItemShop 1.0 不兼容

### ISSUE THREAD

**Issue by aberter0x3f** [Ldcr993519867/BedwarsXP#17]
当我把 BWXP 1.7 插件替换为 2.0 时, `Server thread` throw 出了一个 `EventException` 和一个 `NoSuchMethodError`.

替换后我没有更改任何配置, 在 BWXP 插件的配置目录下产生了两个新文件 `language.yml` 和 `language-en.yml`.

我试过将 BWRel, BWXP, BWIS 三个插件依次 reload, 以及删除所有配置文件后重新 `bwxp enable Game`, 还是会报这两个错误.

我将插件重新换回 1.7 时, 没有报错

使用 2.0 版插件但是删除 bwis 插件后, 没有报错

错误信息 (log 文件):

```
[15:17:34] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to BedwarsItemShop v1.0 BedwarsRel 1.3.6 Addon
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:728) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.EntityPlayer.openContainer(EntityPlayer.java:680) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:184) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at ldcr.BedwarsXP.XPShop.XPItemShop.openCategoryInventory(XPItemShop.java:107) [BedwarsXP-2.0.jar:?]
	at io.github.bedwarsrel.listener.PlayerListener.inGameInteractEntity(PlayerListener.java:145) [BedwarsRel-1.3.6.jar:?]
	at io.github.bedwarsrel.listener.PlayerListener.onInteractEntity(PlayerListener.java:639) [BedwarsRel-1.3.6.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1318) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: ldcr.BedwarsXP.XPShop.XPVillagerTrade.getXP()I
	at com.ram.bedwarsitemshop.xpshop.XPItemShop.toItemStack(XPItemShop.java:200) ~[?:?]
	at com.ram.bedwarsitemshop.xpshop.XPItemShop.openBuyInventory(XPItemShop.java:166) ~[?:?]
	at com.ram.bedwarsitemshop.shop.NewHypixelShop.onOpen(NewHypixelShop.java:118) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-PaperSpigot-f6fba00-9935adc]
	... 29 more
```

版本:

```
bwxp: 2.0
bwis: 1.0
bwrel: 1.3.6
```

**Comment by SakuraKoi** [comment]
本插件版本号在大部分情况下(跑)遵循语义化版本, Bedwars2.0是一个不兼容旧版本的更新

问题出在 XPVillagerTrade.getXP() 在新版本被修改为了 XPVillagerTrade.getXp(), 而你所使用的附属插件使用的是旧版本的API, 导致附属插件找不到方法
计划(2.1版本)添加一个兼容方法来维持附属插件运行, 但建议将这个issue提交至附属插件的开发者处让对方适配, 因为我最近手头开的坑有点多, 可能会咕咕咕一阵子才会发布新版本(

**Comment by SakuraKoi** [comment]
咕? 咕咕! 咕咕咕咕咕!!!
(Fixed, 还有一个issue解决了我就发新版本
