### ISSUE TITLE
2.1和bwsba不兼容

### ISSUE THREAD

**Issue by mom0ka27** [Ldcr993519867/BedwarsXP#18]
### 基础信息
BedwarsXP 2.1
BedwarsRel 1.3.6
Torch-1.8.8
### 附加信息
```
[20:03:13 WARN]: [BedwarsScoreBoardAddon] Task #12 for BedwarsScoreBoardAddon v2.13.1 generated an exception
java.lang.IllegalAccessError: tried to access class ldcr.BedwarsXP.EventListeners from class me.ram.bedwarsscoreboardaddon.Main
        at me.ram.bedwarsscoreboardaddon.Main.init(Main.java:160) ~[?:?]
        at me.ram.bedwarsscoreboardaddon.Main.access$1(Main.java:130) ~[?:?]
        at me.ram.bedwarsscoreboardaddon.Main$1.run(Main.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[%5b%e6%a0%b8%e5%bf%83%5dTorch-1.8.8-R0.1.3-RC4.jar:git-Torch-3135173]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [%5b%e6%a0%b8%e5%bf%83%5dTorch-1.8.8-R0.1.3-RC4.jar:git-Torch-3135173]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) [%5b%e6%a0%b8%e5%bf%83%5dTorch-1.8.8-R0.1.3-RC4.jar:git-Torch-3135173]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:381) [%5b%e6%a0%b8%e5%bf%83%5dTorch-1.8.8-R0.1.3-RC4.jar:git-Torch-3135173]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:732) [%5b%e6%a0%b8%e5%bf%83%5dTorch-1.8.8-R0.1.3-RC4.jar:git-Torch-3135173]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:635) [%5b%e6%a0%b8%e5%bf%83%5dTorch-1.8.8-R0.1.3-RC4.jar:git-Torch-3135173]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
### 能否尝试复现问题及复现问题的方法
安装bwsba-2.13.1和bwxp-2.1，启动时就有
### 服务器所安装的其他可能出现冲突的插件
bwsba
### 你认为的可能造成问题的原因
EventListeners不是public
### 提交建议
把它改成public

**Comment by SakuraKoi** [comment]
这可能是之前某次重构时使用自动代码优化的结果(辣鸡eclipse), 将在下一个版本中修正

**Comment by SakuraKoi** [comment]
已于2.1.1版本修复
