### ISSUE TITLE
插件无法加载

### ISSUE THREAD

**Issue by link-fgfgui** [Ldcr993519867/BedwarsXP#21]
基础信息：
BedwarsRel v1.3.6
BedwarsXP v2.1.2
所有插件：
Plugins (8): BedwarsItemShop, MultiWorld, WorldEdit, BedwarsScoreBoardAddon, ProtocolLib, BedwarsRel, **BedwarsXP**, BedwarsItemAddon
启动命令：
java -jar spigot-1.8.8.jar
插件报错：
`LANG_NOT_FOUND_ERROR_OCCURRED_WHILE_LOADING`
该次启动服务端日志：
```
Loading libraries, please wait...
[13:56:20 INFO]: Starting minecraft server version 1.8.8
[13:56:20 INFO]: Loading properties
[13:56:20 INFO]: Default game type: ADVENTURE
[13:56:20 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:56:21 INFO]: Debug logging is disabled
[13:56:21 INFO]: Using 4 threads for Netty based IO
[13:56:21 INFO]: Server Ping Player Sample Count: 12

[13:56:21 INFO]: Generating keypair
[13:56:21 INFO]: Starting Minecraft server on *:25565
[13:56:21 INFO]: Using default channel type
[13:56:21 INFO]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[13:56:21 INFO]: Set PluginClassLoader as parallel capable
[13:56:21 INFO]: [BedwarsItemShop] Loading BedwarsItemShop v1.1
[13:56:21 INFO]: [MultiWorld] Loading MultiWorld v5.2.6
[13:56:21 INFO]: [WorldEdit] Loading WorldEdit v6.1.3;7a097ca
[13:56:21 INFO]: [BedwarsScoreBoardAddon] Loading BedwarsScoreBoardAddon v2.13.1
[13:56:21 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[13:56:22 INFO]: [BedwarsRel] Loading BedwarsRel v1.3.6
[13:56:22 INFO]: [BedwarsXP] Loading BedwarsXP v2.1.2
[13:56:22 INFO]: [BedwarsItemAddon] Loading BedwarsItemAddon v1.7.0
[13:56:22 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[13:56:22 INFO]: [ProtocolLib] Started structure compiler thread.
[13:56:22 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:56:22 WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:56:22 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:56:22 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:56:22 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:56:22 INFO]: Preparing level "world"
[13:56:22 INFO]: -------- World Settings For [world] --------
[13:56:22 INFO]: Item Merge Radius: 2.5
[13:56:22 INFO]: Item Despawn Rate: 6000
[13:56:22 INFO]: View Distance: 10
[13:56:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:22 INFO]: Arrow Despawn Rate: 1200
[13:56:22 INFO]: Chunks to Grow per Tick: 650
[13:56:22 INFO]: Clear tick list: false
[13:56:22 INFO]: Experience Merge Radius: 3.0
[13:56:22 INFO]: Zombie Aggressive Towards Villager: true
[13:56:22 INFO]: Mob Spawn Range: 4
[13:56:22 INFO]: Anti X-Ray: true
[13:56:22 INFO]:        Engine Mode: 1
[13:56:22 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:22 INFO]:        Replace Blocks: [1, 5]
[13:56:22 INFO]: Cactus Growth Modifier: 100%
[13:56:22 INFO]: Cane Growth Modifier: 100%
[13:56:22 INFO]: Melon Growth Modifier: 100%
[13:56:22 INFO]: Mushroom Growth Modifier: 100%
[13:56:22 INFO]: Pumpkin Growth Modifier: 100%
[13:56:22 INFO]: Sapling Growth Modifier: 100%
[13:56:22 INFO]: Wheat Growth Modifier: 100%
[13:56:22 INFO]: NetherWart Growth Modifier: 100%
[13:56:22 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:22 INFO]: Random Lighting Updates: false
[13:56:22 INFO]: Structure Info Saving: true
[13:56:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:22 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:22 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:22 INFO]: Sending up to 10 chunks per packet
[13:56:22 INFO]: Max TNT Explosions: 100
[13:56:22 INFO]: Max Entity Collisions: 8
[13:56:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:56:22 INFO]: Nerfing mobs spawned from spawners: false
[13:56:22 INFO]: -------- World Settings For [world_nether] --------
[13:56:22 INFO]: Item Merge Radius: 2.5
[13:56:22 INFO]: Item Despawn Rate: 6000
[13:56:22 INFO]: View Distance: 10
[13:56:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:22 INFO]: Arrow Despawn Rate: 1200
[13:56:22 INFO]: Chunks to Grow per Tick: 650
[13:56:22 INFO]: Clear tick list: false
[13:56:22 INFO]: Experience Merge Radius: 3.0
[13:56:22 INFO]: Zombie Aggressive Towards Villager: true
[13:56:22 INFO]: Mob Spawn Range: 4
[13:56:22 INFO]: Anti X-Ray: true
[13:56:22 INFO]:        Engine Mode: 1
[13:56:22 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:22 INFO]:        Replace Blocks: [1, 5]
[13:56:22 INFO]: Cactus Growth Modifier: 100%
[13:56:22 INFO]: Cane Growth Modifier: 100%
[13:56:22 INFO]: Melon Growth Modifier: 100%
[13:56:22 INFO]: Mushroom Growth Modifier: 100%
[13:56:22 INFO]: Pumpkin Growth Modifier: 100%
[13:56:22 INFO]: Sapling Growth Modifier: 100%
[13:56:22 INFO]: Wheat Growth Modifier: 100%
[13:56:22 INFO]: NetherWart Growth Modifier: 100%
[13:56:22 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:22 INFO]: Random Lighting Updates: false
[13:56:22 INFO]: Structure Info Saving: true
[13:56:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:22 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:22 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:22 INFO]: Sending up to 10 chunks per packet
[13:56:22 INFO]: Max TNT Explosions: 100
[13:56:22 INFO]: Max Entity Collisions: 8
[13:56:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:56:22 INFO]: Nerfing mobs spawned from spawners: false
[13:56:22 INFO]: -------- World Settings For [world_the_end] --------
[13:56:22 INFO]: Item Merge Radius: 2.5
[13:56:22 INFO]: Item Despawn Rate: 6000
[13:56:22 INFO]: View Distance: 10
[13:56:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:22 INFO]: Arrow Despawn Rate: 1200
[13:56:22 INFO]: Chunks to Grow per Tick: 650
[13:56:22 INFO]: Clear tick list: false
[13:56:22 INFO]: Experience Merge Radius: 3.0
[13:56:22 INFO]: Zombie Aggressive Towards Villager: true
[13:56:22 INFO]: Mob Spawn Range: 4
[13:56:22 INFO]: Anti X-Ray: true
[13:56:22 INFO]:        Engine Mode: 1
[13:56:22 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:22 INFO]:        Replace Blocks: [1, 5]
[13:56:22 INFO]: Cactus Growth Modifier: 100%
[13:56:22 INFO]: Cane Growth Modifier: 100%
[13:56:22 INFO]: Melon Growth Modifier: 100%
[13:56:22 INFO]: Mushroom Growth Modifier: 100%
[13:56:22 INFO]: Pumpkin Growth Modifier: 100%
[13:56:22 INFO]: Sapling Growth Modifier: 100%
[13:56:22 INFO]: Wheat Growth Modifier: 100%
[13:56:22 INFO]: NetherWart Growth Modifier: 100%
[13:56:22 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:22 INFO]: Random Lighting Updates: false
[13:56:22 INFO]: Structure Info Saving: true
[13:56:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:22 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:22 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:22 INFO]: Sending up to 10 chunks per packet
[13:56:22 INFO]: Max TNT Explosions: 100
[13:56:22 INFO]: Max Entity Collisions: 8
[13:56:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:56:22 INFO]: Nerfing mobs spawned from spawners: false
[13:56:22 INFO]: Preparing start region for level 0 (Seed: 0)
[13:56:22 INFO]: Preparing start region for level 1 (Seed: 1460273514462450178)
[13:56:23 INFO]: Preparing spawn area: 19%
[13:56:24 INFO]: Preparing spawn area: 61%
[13:56:25 INFO]: Preparing start region for level 2 (Seed: 1460273514462450178)
[13:56:26 INFO]: Preparing spawn area: 72%
[13:56:27 INFO]: [BedwarsItemShop] Enabling BedwarsItemShop v1.1
[13:56:27 INFO]: =========================================

[13:56:27 INFO]:

[13:56:27 INFO]:              BedwarsItemShop

[13:56:27 INFO]:

[13:56:27 INFO]:  版本: 1.1

[13:56:27 INFO]:

[13:56:27 INFO]:  作者: Ram

[13:56:27 INFO]:

[13:56:27 INFO]: =========================================

[13:56:27 INFO]: [MultiWorld] Enabling MultiWorld v5.2.6
[13:56:27 INFO]: -------- World Settings For [Hypixel_Bedwars_Waterfall_Map] --------
[13:56:27 INFO]: Item Merge Radius: 2.5
[13:56:27 INFO]: Item Despawn Rate: 6000
[13:56:27 INFO]: View Distance: 10
[13:56:27 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:27 INFO]: Arrow Despawn Rate: 1200
[13:56:27 INFO]: Chunks to Grow per Tick: 650
[13:56:27 INFO]: Clear tick list: false
[13:56:27 INFO]: Experience Merge Radius: 3.0
[13:56:27 INFO]: Zombie Aggressive Towards Villager: true
[13:56:27 INFO]: Mob Spawn Range: 4
[13:56:27 INFO]: Anti X-Ray: true
[13:56:27 INFO]:        Engine Mode: 1
[13:56:27 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:27 INFO]:        Replace Blocks: [1, 5]
[13:56:27 INFO]: Cactus Growth Modifier: 100%
[13:56:27 INFO]: Cane Growth Modifier: 100%
[13:56:27 INFO]: Melon Growth Modifier: 100%
[13:56:27 INFO]: Mushroom Growth Modifier: 100%
[13:56:27 INFO]: Pumpkin Growth Modifier: 100%
[13:56:27 INFO]: Sapling Growth Modifier: 100%
[13:56:27 INFO]: Wheat Growth Modifier: 100%
[13:56:27 INFO]: NetherWart Growth Modifier: 100%
[13:56:27 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:27 INFO]: Random Lighting Updates: false
[13:56:27 INFO]: Structure Info Saving: true
[13:56:27 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:27 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:27 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:27 INFO]: Sending up to 10 chunks per packet
[13:56:27 INFO]: Max TNT Explosions: 100
[13:56:27 INFO]: Max Entity Collisions: 8
[13:56:27 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:56:27 INFO]: Nerfing mobs spawned from spawners: false
[13:56:27 INFO]: Preparing start region for level 3 (Seed: 0)
[13:56:27 INFO]: [MultiWorld] v5.2.6 enabled.
[13:56:27 INFO]: [WorldEdit] Enabling WorldEdit v6.1.3;7a097ca
[13:56:27 INFO]: WEPIF: Using the Bukkit Permissions API.
[13:56:27 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[13:56:27 WARN]: [WorldEdit] WorldEdit has detected you are using Java 7 (based on detected version 17.0.3).
[13:56:27 WARN]: [WorldEdit] WorldEdit will stop supporting Java less than version 8 in the future, due to Java 7 being EOL since April 2015. Please update your server to Java 8.
[13:56:27 INFO]: [BedwarsScoreBoardAddon] Enabling BedwarsScoreBoardAddon v2.13.1
[13:56:27 INFO]: [BedwarsRel] Enabling BedwarsRel v1.3.6
[13:56:27 INFO]: [BedWars] 成功载入了游戏 'Hypixel_Bedwars_Waterfall_Map'！

[13:56:27 INFO]: [BedwarsXP] Enabling BedwarsXP v2.1.2
[13:56:27 INFO]: BedwarsXP >> Loading BedwarsXP... Version.2.1.2

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 正在加载语音文件... | Loading language configuration...

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 正在加载配置文件...

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 已启用经验兑换资源商店

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 死亡扣除 0.0% 经验

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 死亡掉落经验占扣除经验 100.0%

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 最大经验限制已关闭

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 完全经验起床模式已启动

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 开始加载资源价值数据

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 发现资源 bronze 物品:CLAY_BRICK 价值 1

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 发现资源 iron 物品:IRON_INGOT 价值 5

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 发现资源 gold 物品:GOLD_INGOT 价值 10

[13:56:27 INFO]: BedwarsXP >> BedwarsXP >> 发现资源 diamond 物品:DIAMOND 价值 0

[13:56:27 INFO]: BedwarsXP >> ERROR: -----------------------------------

[13:56:27 WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem cannot be cast to class java.util.Map (org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')

[13:56:27 WARN]:        at ldcr.BedwarsXP.Config.loadConfig(Config.java:108)

[13:56:27 WARN]:        at ldcr.BedwarsXP.BedwarsXP.onEnable(BedwarsXP.java:36)

[13:56:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)

[13:56:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)

[13:56:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)

[13:56:27 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)

[13:56:27 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)

[13:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)

[13:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)

[13:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)

[13:56:27 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)

[13:56:27 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)

[13:56:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[13:56:27 INFO]: BedwarsXP >> ERROR: -----------------------------------

[13:56:27 INFO]: BedwarsXP >> ERROR: LANG_NOT_FOUND_ERROR_OCCURRED_WHILE_LOADING

[13:56:27 INFO]: BedwarsXP >> ERROR:    ↓↓ << 请前往此处反馈 >> ↓↓

[13:56:27 INFO]: BedwarsXP >> ERROR:  https://github.com/SakuraKoi/BedwarsXP/issues/1

[13:56:27 INFO]: [BedwarsXP] Disabling BedwarsXP v2.1.2
[13:56:27 INFO]: [BedwarsItemAddon] Enabling BedwarsItemAddon v1.7.0
[13:56:27 INFO]: ========================================

[13:56:27 INFO]:

[13:56:27 INFO]:             BedwarsItemAddon

[13:56:27 INFO]:

[13:56:27 INFO]:  版本: 1.7.0

[13:56:27 INFO]:

[13:56:27 INFO]:  作者: Ram

[13:56:27 INFO]:

[13:56:27 INFO]: ========================================

[13:56:28 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:56:28 INFO]: Done (5.680s)! For help, type "help" or "?"
[13:56:28 INFO]: ===========================================================

[13:56:28 INFO]:

[13:56:28 INFO]:                   BedwarsScoreBoardAddon

[13:56:28 INFO]:

[13:56:28 INFO]:

[13:56:28 INFO]:   版本: 2.13.1

[13:56:28 INFO]:

[13:56:28 INFO]:   作者: Ram

[13:56:28 INFO]:

[13:56:28 INFO]:   网站: https://github.com/TheRamU/BedwarsScoreBoardAddon

[13:56:28 INFO]:

[13:56:28 INFO]: ===========================================================

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 开始加载插件...

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 正在加载配置文件...

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 默认配置文件已保存！

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 配置文件加载成功！

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 正在注册监听器...

[13:56:28 WARN]: [ProtocolLib] [PacketFilterManager] [BedwarsScoreBoardAddon] Unsupported client packet in current Minecraft version: USE_ITEM[PLAY, CLIENT, 46, classNames: [net.minecraft.server.v1_8_R3.PacketPlayInUseItem, net.minecraft.network.protocol.game.ServerboundUseItemPacket, net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock] (unregistered)]
[13:56:28 INFO]: [BedwarsScoreBoardAddon] 监听器注册成功！

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 正在注册指令...

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 指令注册成功！

[13:56:28 INFO]: [BedwarsScoreBoardAddon] 插件加载成功！

>
```
该次启动前BedwarsXP文件夹并不存在
BedwarsRel文件夹中config.yml内容
```
# ###############################
# ####### BEDWARS CONFIG ########
# ##### CREATED BY YANNICI ######
# ###############################
# ###### EXPLANATION ABOUT ######
# ##### EVERY CONFIGURATION #####
# ### YOU CAN FIND ON GITHUB ####
# ############ WIKI #############
# ###############################
# 
# # TYPE HELP # #
# int: number (not decimal)
# string: a normal text (in most cases you can use colorcodes with a beginning ��)
# boolean: true or false (IMPORTANT: true OR false ONLY)
# list<?>: a list of type ? (? is the type of the list items)
# byte: a int but limited between -128 ... 127
# short: a int but limited between -32768 ... 32767
# char: one character

chat-prefix: '&7[&bBedWars&7]&f'
plugin-metrics: true
send-error-data: true
global-messages: true
global-autobalance: false
global-chat-after-end: true
gamelength: 60
allow-crafting: false
overwrite-names: false
lobby-gamemode: 2
holographic-stats:
  show-prefix: false
  name-color: '&7'
  value-color: '&e'
  head-line: Your &eBEDWARS&f stats
teamname-on-tab: false
teamname-in-chat: true
hearts-on-death: true
die-on-void: false
spawn-ressources-in-chest: false
lobbytime: 60
lobby-chatformat: '$player$: $msg$'
ingame-chatformat-all: '[$all$] <$team$>$player$: $msg$'
ingame-chatformat: '<$team$>$player$: $msg$'
game-block: BED_BLOCK
store-game-records: false
store-game-records-holder: false
bed-sound: ENDERDRAGON_GROWL
player-drops: true
keep-inventory-on-death: false
place-in-liquid: true
breakable-blocks:
  use-as-blacklist: false
  list:
  - none
jointeam-entity:
  show-name: true
lobby-scoreboard:
  enabled: true
  title: '&eBEDWARS'
  content:
  - ' '
  - '&fMap: &2$regionname$'
  - '&fPlayers: &2$players$&f/&2$maxplayers$'
  - ' '
  - '&fWaiting ...'
  - ' '
scoreboard:
  format-bed-destroyed: '&c$status$ $team$'
  format-bed-alive: '&a$status$ $team$'
  format-title: '&e$region$&f - $time$'
titles:
  win:
    enabled: true
    title-fade-in: 1.5
    title-stay: 5.0
    title-fade-out: 2.0
    subtitle-fade-in: 1.5
    subtitle-stay: 5.0
    subtitle-fade-out: 2.0
  map:
    enabled: false
    title-fade-in: 1.5
    title-stay: 2.0
    title-fade-out: 1.5
    subtitle-fade-in: 1.5
    subtitle-stay: 2.0
    subtitle-fade-out: 1.5
  countdown:
    enabled: true
    format: '&3{countdown}'
explodes:
  destroy-worldblocks: false
  destroy-beds: false
  drop-blocking: false
friendlyfire: false
friendlybreak: true
gameoverdelay: 10
use-internal-shop: true
save-inventory: true
show-team-in-actionbar: false
chat-to-all-prefix:
- '@'
- '@a'
- '@all'
seperate-game-chat: true
seperate-spectator-chat: false
statistics:
  enabled: false
  show-on-game-end: true
  storage: yaml
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
  player-leave-kills: false
database:
  host: localhost
  port: 3306
  db: database
  user: root
  password: secret
  table-prefix: bw_
spectation-enabled: false
respawn-protection: 0
allowed-commands:
- /help
endgame:
  mainlobby-enabled: false
  all-players-to-mainlobby: false
bungeecord:
  enabled: false
  hubserver: hub
  endgame-in-lobby: true
  full-restart: true
  spigot-restart: true
  motds:
    lobby: |
      $regionname$
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
    running: |
      $regionname$
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
    stopped: |
      $regionname$
      &c[Stopped]
    full: |
      $regionname$
      &7[&b$currentplayers$&7/&b$maxplayers$&7]
locale: zh_CN
resource:
  bronze:
    item:
    - type: CLAY_BRICK
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "\xa74Bronze"
    spawn-interval: 1000
    spread: 1.0
  iron:
    item:
    - type: IRON_INGOT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "\xa77Iron"
    spawn-interval: 1000
    spread: 1.0
  gold:
    item:
    - type: GOLD_INGOT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "\xa76Gold"
    spawn-interval: 10000
    spread: 1.0
  diamond:
    item:
    - type: DIAMOND
    - ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "\xa7bDiamond"
    spawn-interval: 80000
    spread: 0.0
check-updates: false
update-infos: false
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
specials:
  rescue-platform:
    break-time: 10
    using-wait-time: 20
    item: BLAZE_ROD
    can-break: false
    block: SLIME_BLOCK
  protection-wall:
    break-time: 0
    wait-time: 20
    can-break: true
    item: BRICK
    block: SANDSTONE
    width: 5
    height: 3
    distance: 2
  magnetshoe:
    probability: 75
    boots: IRON_BOOTS
  warp-powder:
    show-particles: true
    particle: fireworksSpark
    teleport-time: 6
  trap:
    play-sound: true
    effects:
    - ==: PotionEffect
      effect: 15
      duration: 100
      amplifier: 2
      ambient: true
      has-particles: true
    - ==: PotionEffect
      effect: 18
      duration: 100
      amplifier: 2
      ambient: true
      has-particles: true
    - ==: PotionEffect
      effect: 2
      duration: 100
      amplifier: 2
      ambient: true
      has-particles: true
  tntsheep:
    fuse-time: 8.0
    speed: 0.4
    explosion-factor: 1.0
  arrow-blocker:
    protection-time: 10
    using-wait-time: 30
    item: ender_eye
sign:
  first-line: $title$
  second-line: $regionname$
  third-line: Players &7[&b$currentplayers$&7/&b$maxplayers$&7]
  fourth-line: $status$
player-settings:
  one-stack-on-shift: false
  old-shop-as-default: false
lobbytime-full: 10
hearts-in-halfs: true
spawn-resources-in-chest: true
```

**Comment by SakuraKoi** [comment]
```
  gold:
    item:
    - type: GOLD_INGOT
      amount: 1
      meta:                <--正确格式
        ==: ItemMeta                <--正确格式
        meta-type: UNSPECIFIC                <--正确缩进
        display-name: "\xa76Gold"                <--正确缩进
    spawn-interval: 10000
    spread: 1.0
  diamond:
    item:
    - type: DIAMOND
    - ==: ItemMeta              <-- 错误格式
      meta-type: UNSPECIFIC              <-- 错误缩进
      display-name: "\xa7bDiamond"              <-- 错误缩进
    spawn-interval: 80000
    spread: 0.0
```
你的BedwarsRel插件配置文件中此处配置格式有误
导致BedwarsXP扫描资源物品出错
请参照上方金锭的正确格式, 更正钻石资源的配置

**Comment by SakuraKoi** [comment]
配置问题, Not our fault, 如更正后仍加载出错请reopen
